; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube

upload_protocol = stlink
monitor_speed = 115200

build_flags =
    -Wl,-u,_printf_float
    -DHSE_VALUE=8000000U

    -DTARGET_F446RE

src_filter =
    +<*>
    +<targets/stm32f446re/*>
    -<targets/stm32f303k8/*>

lib_deps = 
    https://github.com/NITOkC-Robocon/RoboconLibrary.git


[env:nucleo_f303k8]
platform = ststm32
board = nucleo_f303k8
framework = stm32cube

upload_protocol = mbed
monitor_speed = 115200

build_flags =
    -Wl,-u,_printf_float
    -DHSE_VALUE=8000000U

    -DTARGET_F303K8

src_filter =
    +<*>
    +<targets/stm32f303k8/*>
    -<targets/stm32f446re/*>

lib_deps = 
    https://github.com/NITOkC-Robocon/RoboconLibrary.git
