#include "core/PinMap.hpp"
#if defined(STM32F446xx)

extern const uint32_t PinPull[PULL_MAX] = {GPIO_NOPULL, GPIO_PULLUP, GPIO_PULLDOWN};

const PinInfo PinMap[PIN_MAX] = {
    //pin_name, port, pin_number,  adc_info,                                                              dac_channel,          tim_info,                                                                                                                                              uart_info                                        I2C_info

    // -------- Port A --------
    { "PA_0",  GPIOA, GPIO_PIN_0,  {nullptr},                                                             {nullptr, 0},         {{TIM2,TIM_CHANNEL_1,GPIO_AF1_TIM2}, {TIM5,TIM_CHANNEL_1,GPIO_AF2_TIM5},   {nullptr,0,0}},                                                            {{UART4,GPIO_AF8_UART4,TX}, {nullptr,0,NONE}},   {nullptr}                        },
    { "PA_1",  GPIOA, GPIO_PIN_1,  {{ADC1, ADC_CHANNEL_1}, {ADC2, ADC_CHANNEL_1}, {ADC3, ADC_CHANNEL_1}}, {nullptr, 0},         {{TIM2,TIM_CHANNEL_2,GPIO_AF1_TIM2}, {TIM5,TIM_CHANNEL_2,GPIO_AF2_TIM5},   {nullptr,0,0}},                                                            {{UART4,GPIO_AF8_UART4,RX}, {nullptr,0,NONE}},   {nullptr}                        },
    { "PA_2",  GPIOA, GPIO_PIN_2,  {{ADC1, ADC_CHANNEL_2}, {ADC2, ADC_CHANNEL_2}, {ADC3, ADC_CHANNEL_2}}, {nullptr, 0},         {{TIM2,TIM_CHANNEL_3,GPIO_AF1_TIM2}, {TIM5,TIM_CHANNEL_3,GPIO_AF2_TIM5},   {TIM9,TIM_CHANNEL_1,GPIO_AF3_TIM9}, {nullptr,0,0}},                        {{USART2,GPIO_AF7_USART2,TX}, {nullptr,0,NONE}}, {nullptr}                        },
    { "PA_3",  GPIOA, GPIO_PIN_3,  {{ADC1, ADC_CHANNEL_3}, {ADC2, ADC_CHANNEL_3}, {ADC3, ADC_CHANNEL_3}}, {nullptr, 0},         {{TIM2,TIM_CHANNEL_4,GPIO_AF1_TIM2}, {TIM5,TIM_CHANNEL_4,GPIO_AF2_TIM5},   {TIM9,TIM_CHANNEL_2,GPIO_AF3_TIM9}, {nullptr,0,0}},                        {{USART2,GPIO_AF7_USART2,RX}, {nullptr,0,NONE}}, {nullptr}                        },
    { "PA_4",  GPIOA, GPIO_PIN_4,  {{ADC1, ADC_CHANNEL_4}, {ADC2, ADC_CHANNEL_4}, {nullptr, 0}},          {DAC, DAC_CHANNEL_1}, {{nullptr,0,0}},                                                                                                                                      {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_5",  GPIOA, GPIO_PIN_5,  {{ADC1, ADC_CHANNEL_5}, {ADC2, ADC_CHANNEL_5}, {nullptr, 0}},          {DAC, DAC_CHANNEL_2}, {{TIM2,TIM_CHANNEL_1,GPIO_AF1_TIM2}, {TIM8,TIM_CHANNEL_1,GPIO_AF3_TIM8},   {nullptr,0,0}},                                                            {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_6",  GPIOA, GPIO_PIN_6,  {{ADC1, ADC_CHANNEL_6}, {ADC2, ADC_CHANNEL_6}, {nullptr, 0}},          {nullptr, 0},         {{TIM3,TIM_CHANNEL_1,GPIO_AF2_TIM3}, {TIM13,TIM_CHANNEL_1,GPIO_AF9_TIM13}, {nullptr,0,0}},                                                            {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_7",  GPIOA, GPIO_PIN_7,  {{ADC1, ADC_CHANNEL_7}, {ADC2, ADC_CHANNEL_7}, {nullptr, 0}},          {nullptr, 0},         {{TIM1,TIM_CHANNEL_1,GPIO_AF1_TIM1}, {TIM3,TIM_CHANNEL_2,GPIO_AF2_TIM3},   {TIM8,TIM_CHANNEL_1,GPIO_AF3_TIM8}, {TIM14,TIM_CHANNEL_1,GPIO_AF9_TIM14}}, {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_8",  GPIOA, GPIO_PIN_8,  {nullptr},                                                             {nullptr, 0},         {{TIM1,TIM_CHANNEL_1,GPIO_AF1_TIM1}, {nullptr,0,0}},                                                                                                  {{nullptr,0,NONE}},                              {{I2C3, GPIO_AF4_I2C3, I2C_SCL}} },
    { "PA_9",  GPIOA, GPIO_PIN_9,  {nullptr},                                                             {nullptr, 0},         {{TIM1,TIM_CHANNEL_2,GPIO_AF1_TIM1}, {nullptr,0,0}},                                                                                                  {{USART1,GPIO_AF7_USART1,TX}, {nullptr,0,NONE}}, {nullptr}                        },
    { "PA_10", GPIOA, GPIO_PIN_10, {nullptr},                                                             {nullptr, 0},         {{TIM1,TIM_CHANNEL_3,GPIO_AF1_TIM1}, {nullptr,0,0}},                                                                                                  {{USART1,GPIO_AF7_USART1,RX}, {nullptr,0,NONE}}, {nullptr}                        },
    { "PA_11", GPIOA, GPIO_PIN_11, {nullptr},                                                             {nullptr, 0},         {{TIM1,TIM_CHANNEL_4,GPIO_AF1_TIM1}, {nullptr,0,0}},                                                                                                  {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_12", GPIOA, GPIO_PIN_12, {nullptr},                                                             {nullptr, 0},         {{nullptr,0,0}},                                                                                                                                      {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_13", GPIOA, GPIO_PIN_13, {nullptr},                                                             {nullptr, 0},         {{nullptr,0,0}},                                                                                                                                      {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_14", GPIOA, GPIO_PIN_14, {nullptr},                                                             {nullptr, 0},         {{nullptr,0,0}},                                                                                                                                      {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PA_15", GPIOA, GPIO_PIN_15, {nullptr},                                                             {nullptr, 0},         {{TIM2,TIM_CHANNEL_1,GPIO_AF1_TIM2}, {nullptr,0,0}},                                                                                                  {{nullptr,0,NONE}},                              {nullptr}                        },

    // -------- Port B --------
    { "PB_0",  GPIOB, GPIO_PIN_0,  {{ADC1, ADC_CHANNEL_8}, {ADC2, ADC_CHANNEL_8}, {nullptr, 0}},   {nullptr, 0}, {{TIM1,TIM_CHANNEL_2,GPIO_AF1_TIM1}, {TIM3,TIM_CHANNEL_3,GPIO_AF2_TIM3}, {TIM8,TIM_CHANNEL_2,GPIO_AF3_TIM8}, {nullptr,0,0}},   {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_1",  GPIOB, GPIO_PIN_1,  {{ADC1, ADC_CHANNEL_9}, {ADC2, ADC_CHANNEL_9}, {nullptr, 0}},   {nullptr, 0}, {{TIM1,TIM_CHANNEL_3,GPIO_AF1_TIM1}, {TIM3,TIM_CHANNEL_4,GPIO_AF2_TIM3}, {TIM8,TIM_CHANNEL_3,GPIO_AF3_TIM8}, {nullptr,0,0}},   {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_2",  GPIOB, GPIO_PIN_2,  {nullptr},                                                      {nullptr, 0}, {{TIM2,TIM_CHANNEL_4,GPIO_AF1_TIM2}, {nullptr,0,0}},                                                                           {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_3",  GPIOB, GPIO_PIN_3,  {nullptr},                                                      {nullptr, 0}, {{TIM2,TIM_CHANNEL_2,GPIO_AF1_TIM2}, {nullptr,0,0}},                                                                           {{nullptr,0,NONE}},                              {{I2C2, GPIO_AF4_I2C2, I2C_SDA}} },
    { "PB_4",  GPIOB, GPIO_PIN_4,  {nullptr},                                                      {nullptr, 0}, {{TIM3,TIM_CHANNEL_1,GPIO_AF2_TIM3}, {nullptr,0,0}},                                                                           {{nullptr,0,NONE}},                              {{I2C3, GPIO_AF4_I2C3, I2C_SDA}} },
    { "PB_5",  GPIOB, GPIO_PIN_5,  {nullptr},                                                      {nullptr, 0}, {{TIM3,TIM_CHANNEL_2,GPIO_AF2_TIM3}, {nullptr,0,0}},                                                                           {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_6",  GPIOB, GPIO_PIN_6,  {nullptr},                                                      {nullptr, 0}, {{TIM4,TIM_CHANNEL_1,GPIO_AF2_TIM4}, {nullptr,0,0}},                                                                           {{USART1,GPIO_AF7_USART1,TX}, {nullptr,0,NONE}}, {{I2C1, GPIO_AF4_I2C1, I2C_SCL}} },
    { "PB_7",  GPIOB, GPIO_PIN_7,  {nullptr},                                                      {nullptr, 0}, {{TIM4,TIM_CHANNEL_2,GPIO_AF2_TIM4}, {nullptr,0,0}},                                                                           {{USART1,GPIO_AF7_USART1,RX}, {nullptr,0,NONE}}, {{I2C1, GPIO_AF4_I2C1, I2C_SDA}} },
    { "PB_8",  GPIOB, GPIO_PIN_8,  {nullptr},                                                      {nullptr, 0}, {{TIM2,TIM_CHANNEL_1,GPIO_AF1_TIM2}, {TIM4,TIM_CHANNEL_3,GPIO_AF2_TIM4}, {TIM10,TIM_CHANNEL_1,GPIO_AF3_TIM10}, {nullptr,0,0}}, {{nullptr,0,NONE}},                              {{I2C1, GPIO_AF4_I2C1, I2C_SCL}} },
    { "PB_9",  GPIOB, GPIO_PIN_9,  {nullptr},                                                      {nullptr, 0}, {{TIM2,TIM_CHANNEL_2,GPIO_AF1_TIM2}, {TIM4,TIM_CHANNEL_4,GPIO_AF2_TIM4}, {TIM11,TIM_CHANNEL_1,GPIO_AF3_TIM11}, {nullptr,0,0}}, {{nullptr,0,NONE}},                              {{I2C1, GPIO_AF4_I2C1, I2C_SDA}} },
    { "PB_10", GPIOB, GPIO_PIN_10, {nullptr},                                                      {nullptr, 0}, {{TIM2,TIM_CHANNEL_3,GPIO_AF1_TIM2}, {nullptr,0,0}},                                                                           {{USART3,GPIO_AF7_USART3,TX}, {nullptr,0,NONE}}, {{I2C2, GPIO_AF4_I2C2, I2C_SCL}} },
    { "PB_12", GPIOB, GPIO_PIN_12, {nullptr},                                                      {nullptr, 0}, {{nullptr,0,0}},                                                                                                               {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_13", GPIOB, GPIO_PIN_13, {nullptr},                                                      {nullptr, 0}, {{TIM1,TIM_CHANNEL_1,GPIO_AF1_TIM1}, {nullptr,0,0}},                                                                           {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_14", GPIOB, GPIO_PIN_14, {nullptr},                                                      {nullptr, 0}, {{TIM1,TIM_CHANNEL_2,GPIO_AF1_TIM1}, {TIM8,TIM_CHANNEL_2,GPIO_AF3_TIM8}, {TIM12,TIM_CHANNEL_1,GPIO_AF9_TIM12}, {nullptr,0,0}}, {{nullptr,0,NONE}},                              {nullptr}                        },
    { "PB_15", GPIOB, GPIO_PIN_15, {nullptr},                                                      {nullptr, 0}, {{TIM1,TIM_CHANNEL_3,GPIO_AF1_TIM1}, {TIM8,TIM_CHANNEL_3,GPIO_AF3_TIM8}, {TIM12,TIM_CHANNEL_2,GPIO_AF9_TIM12}, {nullptr,0,0}}, {{nullptr,0,NONE}},                              {nullptr}                        },

    // -------- Port C --------
    { "PC_0",  GPIOC, GPIO_PIN_0,  {{ADC1, ADC_CHANNEL_10}, {ADC2, ADC_CHANNEL_10}, {ADC3, ADC_CHANNEL_10}}, {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_1",  GPIOC, GPIO_PIN_1,  {{ADC1, ADC_CHANNEL_11}, {ADC2, ADC_CHANNEL_11}, {ADC3, ADC_CHANNEL_11}}, {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_2",  GPIOC, GPIO_PIN_2,  {{ADC1, ADC_CHANNEL_12}, {ADC2, ADC_CHANNEL_12}, {ADC3, ADC_CHANNEL_12}}, {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_3",  GPIOC, GPIO_PIN_3,  {{ADC1, ADC_CHANNEL_13}, {ADC2, ADC_CHANNEL_13}, {ADC3, ADC_CHANNEL_13}}, {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_4",  GPIOC, GPIO_PIN_4,  {{ADC1, ADC_CHANNEL_14}, {ADC2, ADC_CHANNEL_14}, {nullptr, 0}},           {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_5",  GPIOC, GPIO_PIN_5,  {{ADC1, ADC_CHANNEL_15}, {ADC2, ADC_CHANNEL_15}, {nullptr, 0}},           {nullptr, 0}, {{nullptr,0,0}},                                                                         {{USART3,GPIO_AF7_USART3,RX}, {nullptr,0,NONE}},          {nullptr}                        },
    { "PC_6",  GPIOC, GPIO_PIN_6,  {nullptr},                                                                {nullptr, 0}, {{TIM3,TIM_CHANNEL_1,GPIO_AF2_TIM3}, {TIM8,TIM_CHANNEL_1,GPIO_AF3_TIM8}, {nullptr,0,0}}, {{USART6,GPIO_AF8_USART6,TX}, {nullptr,0,NONE}},          {nullptr}                        },
    { "PC_7",  GPIOC, GPIO_PIN_7,  {nullptr},                                                                {nullptr, 0}, {{TIM3,TIM_CHANNEL_2,GPIO_AF2_TIM3}, {TIM8,TIM_CHANNEL_2,GPIO_AF3_TIM8}, {nullptr,0,0}}, {{USART6,GPIO_AF8_USART6,RX}, {nullptr,0,NONE}},          {nullptr}                        },
    { "PC_8",  GPIOC, GPIO_PIN_8,  {nullptr},                                                                {nullptr, 0}, {{TIM3,TIM_CHANNEL_3,GPIO_AF2_TIM3}, {TIM8,TIM_CHANNEL_3,GPIO_AF3_TIM8}, {nullptr,0,0}}, {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_9",  GPIOC, GPIO_PIN_9,  {nullptr},                                                                {nullptr, 0}, {{TIM3,TIM_CHANNEL_4,GPIO_AF2_TIM3}, {TIM8,TIM_CHANNEL_4,GPIO_AF3_TIM8}, {nullptr,0,0}}, {{nullptr,0,NONE}},                                       {{I2C3, GPIO_AF4_I2C3, I2C_SDA}} },
    { "PC_10", GPIOC, GPIO_PIN_10, {nullptr},                                                                {nullptr, 0}, {{nullptr,0,0}},                                                                         {{USART3,GPIO_AF7_USART3,TX}, {UART4,GPIO_AF8_UART4,TX}}, {nullptr}                        },
    { "PC_11", GPIOC, GPIO_PIN_11, {nullptr},                                                                {nullptr, 0}, {{nullptr,0,0}},                                                                         {{USART3,GPIO_AF7_USART3,RX}, {UART4,GPIO_AF8_UART4,RX}}, {nullptr}                        },
    { "PC_12", GPIOC, GPIO_PIN_12, {nullptr},                                                                {nullptr, 0}, {{nullptr,0,0}},                                                                         {{UART5,GPIO_AF8_UART5,TX}, {nullptr,0,NONE}},            {{I2C2, GPIO_AF4_I2C2, I2C_SDA}} },
    { "PC_13", GPIOC, GPIO_PIN_13, {nullptr},                                                                {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_14", GPIOC, GPIO_PIN_14, {nullptr},                                                                {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },
    { "PC_15", GPIOC, GPIO_PIN_15, {nullptr},                                                                {nullptr, 0}, {{nullptr,0,0}},                                                                         {{nullptr,0,NONE}},                                       {nullptr}                        },

    // -------- Port D --------
    { "PD_2", GPIOD, GPIO_PIN_2, {nullptr}, {nullptr, 0}, {{nullptr,0,0}}, {{UART5,GPIO_AF8_UART5,RX}}, {nullptr} },
};

#endif